# Generated by Django 2.0.3 on 2018-03-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20180316_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
