# Generated by Django 2.0.3 on 2018-03-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20180316_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
